//! SWAI — Council progressive SSE streaming events.
//!
//! Emits Server-Sent Events (SSE) for live council deliberation updates,
//! allowing API clients to receive real-time progress during long runs.
//! Follows Anthropic / OpenAI streaming conventions with custom event types.

use chrono::Utc;
use serde::{Deserialize, Serialize};
use std::fmt::Write;

/// SSE event types emitted by the council streaming engine.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum CouncilStreamEvent {
    /// Stage progression update (stage name, active model, estimated time).
    Status {
        stage: String,
        model_id: String,
        elapsed_secs: f64,
    },
    /// Initial draft generated by stage 1.
    Draft { draft_text: String, model_id: String },
    /// Auditor feedback and critique notes.
    Critique {
        auditor_index: usize,
        critique: String,
        model_id: String,
    },
    /// Final synthesized chunk token for the output stream.
    Chunk { text: String },
    /// Stream completion marker.
    Done,
}

/// Format a CouncilStreamEvent as an SSE-formatted string.
///
/// Each event is formatted as:
/// ```text
/// event: <event_type>
/// data: <json_payload>
///
/// ```
pub fn format_sse_event(event: &CouncilStreamEvent, sequence: u64) -> String {
    let mut sse = String::new();

    match event {
        CouncilStreamEvent::Status {
            stage,
            model_id,
            elapsed_secs,
        } => {
            writeln!(sse, "event: council_status").unwrap();
            let data = serde_json::json!({
                "sequence": sequence,
                "stage": stage,
                "model_id": model_id,
                "elapsed_secs": elapsed_secs,
                "timestamp": Utc::now().to_rfc3339(),
            });
            writeln!(sse, "data: {}", data).unwrap();
        }
        CouncilStreamEvent::Draft { draft_text, model_id } => {
            writeln!(sse, "event: council_draft").unwrap();
            let data = serde_json::json!({
                "sequence": sequence,
                "model_id": model_id,
                "draft": draft_text,
                "timestamp": Utc::now().to_rfc3339(),
            });
            writeln!(sse, "data: {}", data).unwrap();
        }
        CouncilStreamEvent::Critique {
            auditor_index,
            critique,
            model_id,
        } => {
            writeln!(sse, "event: council_critique").unwrap();
            let data = serde_json::json!({
                "sequence": sequence,
                "auditor_index": auditor_index,
                "model_id": model_id,
                "critique": critique,
                "timestamp": Utc::now().to_rfc3339(),
            });
            writeln!(sse, "data: {}", data).unwrap();
        }
        CouncilStreamEvent::Chunk { text } => {
            writeln!(sse, "event: council_chunk").unwrap();
            let data = serde_json::json!({
                "sequence": sequence,
                "text": text,
                "timestamp": Utc::now().to_rfc3339(),
            });
            writeln!(sse, "data: {}", data).unwrap();
        }
        CouncilStreamEvent::Done => {
            writeln!(sse, "event: council_done").unwrap();
            let data = serde_json::json!({
                "sequence": sequence,
                "timestamp": Utc::now().to_rfc3339(),
            });
            writeln!(sse, "data: {}", data).unwrap();
        }
    }

    // End the SSE event with double newline per SSE spec.
    sse.push_str("\n");
    sse
}

/// Encode a stream of events into a complete SSE message bundle.
pub fn encode_stream_events(events: &[CouncilStreamEvent]) -> String {
    let mut output = String::new();
    for (i, event) in events.iter().enumerate() {
        output.push_str(&format_sse_event(event, i as u64 + 1));
    }
    output
}
